name: Java CI with Maven and MariaDB

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-22.04
    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3307:3306
        env:
          MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'  # Explicitly allow an empty root password
          MARIADB_DATABASE: cleancode
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root -ptest --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Wait for MariaDB
        run: |
          for i in {1..10}; do
            if mysqladmin ping -h 127.0.0.1 -P 3306 -uroot -ptest --silent; then
              echo "MariaDB is ready";
              break;
            fi
            echo "Waiting for MariaDB to be ready...";
            sleep 5;
          done

      - name: Debug MariaDB Logs on Failure
        if: failure()
        run: |
          echo "Capturing MariaDB logs due to failure...";
          docker ps -a
          docker logs $(docker ps -aqf "ancestor=mariadb:latest")

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test
        env:
          SPRING_DATASOURCE_URL: jdbc:mariadb://127.0.0.1:3307/cleancode
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: ""

