name: Java CI with Maven

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

# Définition des jobs du workflow
jobs:
  build:
    runs-on: ubuntu-22.04
    services:
       mariadb:
        image: mariadb:latest  # Official MariaDB Docker image
        ports:
          - 3306:3306  # Map port 3306
        env:
          MARIADB_ROOT_PASSWORD: rootpassword  # Root password for MariaDB
          MARIADB_DATABASE: cleancode  # Name of the database
          MARIADB_USER: root  # MariaDB user
          MARIADB_PASSWORD: test  # Password for the MariaDB user
        options: >
          --health-cmd="mysqladmin ping --silent" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5  # Health check options

    # Étapes du job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # OpenJDK distribution
          java-version: 17 # Version du JDK

      - name: Build with Maven
        run: mvn clean install -DskipTests=true

      - name: Run tests
        run: mvn test
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/testdb  # URL de connexion à MySQL
          SPRING_DATASOURCE_USERNAME: testuser  # Utilisateur MySQL
          SPRING_DATASOURCE_PASSWORD: testpassword  # Mot de passe MySQL
