name: Java CI with Maven

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

# Définition des jobs du workflow
jobs:
  build:
    runs-on: ubuntu-22.04
    services:
      mariadb:
        image: mariadb:latest  # L'image Docker officielle de MariaDB
        ports:
          - 3306:3306  # Mappe le port 3306 du container au port 3306 de la machine hôte
        env:
          MARIADB_ROOT_PASSWORD: rootpassword  # Mot de passe root pour MariaDB
          MARIADB_DATABASE: testdb  # Nom de la base de données à créer
          MARIADB_USER: testuser  # Utilisateur MariaDB
          MARIADB_PASSWORD: testpassword  # Mot de passe de l'utilisateur MariaDB
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=5  # Vérification de la santé de MariaDB

    # Étapes du job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # OpenJDK distribution
          java-version: 17 # Version du JDK

      - name: Build with Maven
        run: mvn clean install -DskipTests=true

      - name: Run tests
        run: mvn test
        env:
          SPRING_DATASOURCE_URL: jdbc:mariadb://localhost:3306/testdb  # URL de connexion à MariaDB
          SPRING_DATASOURCE_USERNAME: testuser  # Utilisateur MariaDB
          SPRING_DATASOURCE_PASSWORD: testpassword  # Mot de passe MariaDB
