name: Java CI with Maven

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

# Définition des jobs du workflow
jobs:
  build:
    runs-on: ubuntu-22.04

    # Étapes du job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # OpenJDK distribution
          java-version: 17 # Version du JDK

      - name: Build with Maven
        run: mvn clean install -DskipTests=true

      - name: Run tests
        run: mvn test
