name: Java CI with Maven and MariaDB

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-22.04
    services:
      mariadb:
        image: mariadb:10.9
        ports:
          - 3306:3306
        env:
          MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
          MARIADB_ROOT_PASSWORD: ""
          MARIADB_DATABASE: cleancode
        options: >-
          --health-cmd="mysqladmin ping -h localhost || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Wait for MariaDB to be ready
        run: |
          echo "Waiting for MariaDB to be healthy..."
          for i in {1..30}; do
            if docker inspect --format='{{.State.Health.Status}}' $(docker ps -aqf "ancestor=mariadb:latest") | grep -q 'healthy'; then
              echo "MariaDB is healthy!"
              break
            fi
            echo "MariaDB not healthy yet, retrying in 5 seconds..."
            sleep 5
          done

      - name: Debug MariaDB Logs on Failure
        if: failure()
        run: |
          echo "Capturing MariaDB logs due to failure..."
          docker ps -a
          docker logs $(docker ps -aqf "ancestor=mariadb:latest")

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test
        env:
          SPRING_DATASOURCE_URL: jdbc:mariadb://127.0.0.1:3306/cleancode
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: ""


