name: Java CI with Maven

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-22.04
    services:
      mariadb:
        image: mariadb:latest  # Official MariaDB Docker image
        ports:
          - 3306:3306  # Map port 3306
        env:
          MARIADB_ROOT_PASSWORD: rootpassword  # Root password for MariaDB
          MARIADB_DATABASE: cleancode  # Database name
          MARIADB_USER: root  # MariaDB user
          MARIADB_PASSWORD: test  # MariaDB password
        options: >
          --health-cmd="mysqladmin ping --silent" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # OpenJDK distribution
          java-version: 17  # JDK version

      - name: Build with Maven
        run: mvn clean install -DskipTests=true

      - name: Run tests
        run: mvn test
        env:
          SPRING_DATASOURCE_URL: jdbc:mariadb://localhost:3306/cleancode  # MariaDB connection URL
          SPRING_DATASOURCE_USERNAME: root  # MariaDB username
          SPRING_DATASOURCE_PASSWORD:  "" # MariaDB password
